# Generated by Django 5.2.5 on 2025-10-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sales', 'Sales'), ('products', 'Products'), ('categories', 'Categories'), ('clients', 'Clients'), ('employees', 'Employees'), ('workshop', 'Workshop')], max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CashShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_shift_id', models.CharField(max_length=100, unique=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('cash_start', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_end', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_sell_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_sell_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_collection', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user_id_start', models.IntegerField(blank=True, null=True)),
                ('user_id_end', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('category_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(default=1)),
                ('firstname', models.CharField(default='')),
                ('lastname', models.CharField(default='')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transactions', models.IntegerField(default=0)),
                ('avg_check', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payments_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.IntegerField()),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_delivery_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_delivery_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tips', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(blank=True, null=True)),
                ('date_start', models.DateTimeField()),
                ('date_close', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('pay_type', models.IntegerField(default=0)),
                ('payed_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spot_id', models.IntegerField(default=1)),
                ('transaction_comment', models.CharField(blank=True, max_length=225, null=True)),
                ('reason', models.CharField(default='')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client_firstname', models.CharField(blank=True, max_length=225)),
                ('client_lastname', models.CharField(blank=True, max_length=225)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_id', models.CharField(blank=True, default='', null=True)),
                ('service_mode', models.IntegerField(default=0)),
                ('processing_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.IntegerField(unique=True)),
                ('workshop_name', models.CharField(max_length=255)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='poster_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fiscal', models.IntegerField(default=1)),
                ('workshop', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='poster_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='poster_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('count', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('product_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payed_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('workshop', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_service', models.CharField(blank=True, max_length=255, null=True)),
                ('tips', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shift_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='poster_api.shiftsale')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_history', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('value', models.CharField(default='')),
                ('value2', models.CharField(default='')),
                ('value3', models.CharField(default='')),
                ('value_text', models.JSONField(blank=True, null=True)),
                ('spot_tablet_id', models.IntegerField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='poster_api.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('workshop', models.IntegerField(default=0)),
                ('payed_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_entries', to='poster_api.clients')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_entries', to='poster_api.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='poster_api.transactions')),
            ],
        ),
    ]
