# Generated by Django 5.2.5 on 2025-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_shift_id', models.CharField(max_length=100, unique=True)),
                ('organization_id', models.CharField(max_length=100)),
                ('cash_start', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_end', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
