# Generated by Django 5.2.5 on 2025-10-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0002_spot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsrecord',
            options={'verbose_name': 'Analytics Record', 'verbose_name_plural': 'Analytics Records'},
        ),
        migrations.AlterModelOptions(
            name='cashshiftreport',
            options={'verbose_name': 'Cash Shift Report', 'verbose_name_plural': 'Cash Shift Reports'},
        ),
        migrations.AlterModelOptions(
            name='categoriessales',
            options={'verbose_name': 'Category Sale Aggregate', 'verbose_name_plural': 'Category Sale Aggregates'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='payments_id',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='productsales',
            options={'verbose_name': 'Product Sale Aggregate', 'verbose_name_plural': 'Product Sale Aggregates'},
        ),
        migrations.AlterModelOptions(
            name='shiftsale',
            options={'verbose_name': 'Aggregated Shift Sale', 'verbose_name_plural': 'Aggregated Shift Sales'},
        ),
        migrations.AlterModelOptions(
            name='shiftsaleitem',
            options={'verbose_name': 'Aggregated Shift Item', 'verbose_name_plural': 'Aggregated Shift Items'},
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'verbose_name': 'Transaction History', 'verbose_name_plural': 'Transaction Histories'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionsproducts',
            options={'verbose_name': 'Transaction Product', 'verbose_name_plural': 'Transaction Products'},
        ),
        migrations.AlterUniqueTogether(
            name='analyticsrecord',
            unique_together={('type', 'entity_id', 'date')},
        ),
    ]
