# Generated by Django 5.2.5 on 2025-09-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0002_cashshiftreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashshiftreport',
            old_name='closed_at',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='cashshiftreport',
            old_name='created_at',
            new_name='date_start',
        ),
        migrations.RemoveField(
            model_name='cashshiftreport',
            name='organization_id',
        ),
    ]
