# Generated by Django 5.2.5 on 2025-09-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0003_rename_closed_at_cashshiftreport_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_shift_id', models.IntegerField()),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_delivery_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_delivery_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tips', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_service', models.CharField(blank=True, max_length=255, null=True)),
                ('shift_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='poster_api.shiftsale')),
            ],
        ),
    ]
