# Generated by Django 5.2.5 on 2025-10-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0003_alter_analyticsrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
