# Generated by Django 5.2.5 on 2025-09-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0004_shiftsale_shiftsaleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashshiftreport',
            name='sales',
        ),
        migrations.AddField(
            model_name='cashshiftreport',
            name='amount_collection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashshiftreport',
            name='amount_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashshiftreport',
            name='amount_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashshiftreport',
            name='amount_sell_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashshiftreport',
            name='amount_sell_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashshiftreport',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashshiftreport',
            name='user_id_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashshiftreport',
            name='user_id_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
