# Generated by Django 5.2.5 on 2025-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0005_remove_cashshiftreport_sales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_id', models.IntegerField(unique=True)),
                ('workshop_name', models.CharField(max_length=255)),
                ('delete', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='category',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='transactions',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
