# Generated by Django 5.2.5 on 2025-09-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0006_workshop_delete_department_category_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=None),
        ),
    ]
