# Generated by Django 5.2.5 on 2025-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0007_category_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
