# Generated by Django 5.2.5 on 2025-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0008_alter_category_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=None, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count', models.IntegerField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='profit',
        ),
    ]
