# Generated by Django 5.2.5 on 2025-09-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0009_categoriessales_remove_category_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriessales',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='poster_api.category'),
        ),
    ]
