# Generated by Django 5.2.5 on 2025-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0010_alter_categoriessales_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriessales',
            name='category_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(unique=True),
        ),
    ]
