# Generated by Django 5.2.5 on 2025-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0011_alter_categoriessales_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=None),
        ),
    ]
