# Generated by Django 5.2.5 on 2025-09-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0012_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(unique=True)),
                ('firstname', models.CharField(default='')),
                ('lastname', models.CharField(default='')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transactions', models.IntegerField(default=0)),
                ('avg_check', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payments_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_history', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_text', models.JSONField(blank=True, null=True)),
                ('spot_tablet_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(unique=True)),
                ('date_start', models.DateTimeField()),
                ('date_close', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('pay_type', models.IntegerField(default=0)),
                ('payed_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spot_id', models.IntegerField(default=1)),
                ('transaction_comment', models.CharField(blank=True, max_length=225, null=True)),
                ('reason', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client_firstname', models.CharField(blank=True, max_length=225)),
                ('client_lastname', models.CharField(blank=True, max_length=225)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_id', models.IntegerField(default=0)),
                ('service_mode', models.IntegerField(default=0)),
                ('processing_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('workshop', models.IntegerField(default=0)),
                ('payed_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_entries', to='poster_api.clients')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='categoriessales',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='categoriessales',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_profit',
        ),
        migrations.AddField(
            model_name='categoriessales',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='poster_api.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='poster_api.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='fiscal',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='workshop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='type',
            field=models.CharField(choices=[('sales', 'Sales'), ('products', 'Products'), ('categories', 'Categories'), ('clients', 'Clients'), ('employees', 'Employees'), ('workshop', 'Workshop')], max_length=50),
        ),
        migrations.AlterField(
            model_name='categoriessales',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='poster_api.product'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='poster_api.transactions'),
        ),
        migrations.AddField(
            model_name='transactionsproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_entries', to='poster_api.product'),
        ),
        migrations.AddField(
            model_name='transactionsproducts',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='poster_api.transactions'),
        ),
    ]
