# Generated by Django 5.2.5 on 2025-09-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0013_clients_payments_id_productsales_transactionhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriessales',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='categoriessales',
            name='category_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='categoriessales',
            name='category_name',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
