# Generated by Django 5.2.5 on 2025-09-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0015_remove_product_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='client_id',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='reason',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
