# Generated by Django 5.2.5 on 2025-09-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0016_alter_clients_client_id_alter_transactions_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='value',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='value2',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='value3',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='client_id',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
