# Generated by Django 5.2.5 on 2025-09-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0017_alter_transactionhistory_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftsale',
            old_name='poster_shift_id',
            new_name='shift_id',
        ),
    ]
