# Generated by Django 5.2.5 on 2025-09-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0018_rename_poster_shift_id_shiftsale_shift_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftsaleitem',
            old_name='price',
            new_name='product_sum',
        ),
    ]
