# Generated by Django 5.2.5 on 2025-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0019_rename_price_shiftsaleitem_product_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftsaleitem',
            old_name='department',
            new_name='workshop',
        ),
        migrations.AddField(
            model_name='shiftsaleitem',
            name='tips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
