# Generated by Django 5.2.5 on 2025-10-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0020_rename_department_shiftsaleitem_workshop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftsaleitem',
            old_name='shift_sale',
            new_name='shift_sale_id',
        ),
    ]
