# Generated by Django 5.2.5 on 2025-10-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0022_rename_shift_sale_id_shiftsaleitem_shift_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftsaleitem',
            old_name='quantity',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='shiftsaleitem',
            old_name='paid_sum',
            new_name='payed_sum',
        ),
    ]
