# Generated by Django 5.2.5 on 2025-10-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0023_rename_quantity_shiftsaleitem_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftsaleitem',
            old_name='shift_sale',
            new_name='shift_sale_id',
        ),
    ]
