# Generated by Django 5.2.5 on 2025-10-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0024_rename_shift_sale_shiftsaleitem_shift_sale_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftsaleitem',
            old_name='shift_sale_id',
            new_name='shift_sale',
        ),
    ]
