# Generated by Django 5.2.5 on 2025-10-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0025_rename_shift_sale_id_shiftsaleitem_shift_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
