# Generated by Django 5.2.5 on 2025-10-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0026_rename_name_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriessales',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='categoriessales',
            name='category_name',
        ),
        migrations.AddField(
            model_name='categoriessales',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='poster_api.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
