# Generated by Django 5.2.5 on 2025-10-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poster_api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalarySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_per_shift', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('workshops', models.ManyToManyField(blank=True, to='poster_api.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRuleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_api.product')),
                ('salary_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryrule')),
            ],
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='products',
            field=models.ManyToManyField(blank=True, through='salary.SalaryRuleProduct', to='poster_api.product'),
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_api.cashshiftreport')),
            ],
            options={
                'unique_together': {('shift', 'employee')},
            },
        ),
    ]
