# Generated by Django 5.2.5 on 2025-10-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecord',
            name='amount',
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='bonus_part',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2004-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='fixed_part',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='percent_part',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
