# Generated by Django 5.2.5 on 2025-09-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0006_workshop_delete_department_category_profit_and_more'),
        ('salary', '0001_initial'),
        ('users', '0004_role_alter_user_role_employee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('shift', 'employee')},
        ),
        migrations.RemoveField(
            model_name='salaryrule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='salaryrule',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salaryrule',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salaryrule',
            name='rule_type',
        ),
        migrations.RemoveField(
            model_name='salaryrule',
            name='value',
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='fixed_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='fixed_per_shift',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_api.cashshiftreport'),
        ),
        migrations.CreateModel(
            name='MonthlySalarySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='created_at',
        ),
    ]
