# Generated by Django 5.2.5 on 2025-09-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_salaryrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryrule',
            old_name='category_name',
            new_name='workshop_name',
        ),
    ]
