# Generated by Django 5.2.5 on 2025-10-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0003_alter_analyticsrecord_options_and_more'),
        ('salary', '0002_remove_salaryrecord_amount_salaryrecord_bonus_part_and_more'),
        ('shift', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlysalarysummary',
            options={'ordering': ['-month', 'employee__name'], 'verbose_name': 'Monthly Salary Summary', 'verbose_name_plural': 'Monthly Salary Summaries'},
        ),
        migrations.AlterModelOptions(
            name='salaryrecord',
            options={'verbose_name': 'Salary Record', 'verbose_name_plural': 'Salary Records'},
        ),
        migrations.AlterModelOptions(
            name='salaryrule',
            options={'verbose_name': 'Salary Rule', 'verbose_name_plural': 'Salary Rules'},
        ),
        migrations.AlterModelOptions(
            name='salaryruleproduct',
            options={'verbose_name': 'Salary Product Bonus', 'verbose_name_plural': 'Salary Product Bonuses'},
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='comment',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='write_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysalarysummary',
            unique_together={('employee', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryruleproduct',
            unique_together={('salary_rule', 'product')},
        ),
    ]
