# Generated by Django 5.2.5 on 2025-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_monthlysalarysummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Detail (JSON)'),
        ),
    ]
