# Generated by Django 5.2.5 on 2025-09-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0019_rename_price_shiftsaleitem_product_sum'),
        ('salary', '0003_rename_category_name_salaryrule_workshop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrule',
            name='workshop_name',
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='workshop_name_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poster_api.workshop'),
        ),
    ]
