# Generated by Django 5.2.5 on 2025-09-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_remove_salaryrule_workshop_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryrule',
            old_name='workshop_name_id',
            new_name='workshop',
        ),
    ]
