# Generated by Django 5.2.5 on 2025-09-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0019_rename_price_shiftsaleitem_product_sum'),
        ('salary', '0005_rename_workshop_name_id_salaryrule_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrule',
            name='workshop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='poster_api.workshop'),
        ),
    ]
