# Generated by Django 5.2.5 on 2025-09-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0019_rename_price_shiftsaleitem_product_sum'),
        ('salary', '0006_alter_salaryrule_workshop'),
        ('users', '0004_role_alter_user_role_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrule',
            name='fixed_per_item',
        ),
        migrations.RemoveField(
            model_name='salaryrule',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='salaryrule',
            name='workshop',
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='workshops',
            field=models.ManyToManyField(blank=True, to='poster_api.workshop'),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.CreateModel(
            name='SalaryRuleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_api.product')),
                ('salary_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.salaryrule')),
            ],
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='products',
            field=models.ManyToManyField(blank=True, through='salary.SalaryRuleProduct', to='poster_api.product'),
        ),
    ]
