# Generated by Django 5.2.5 on 2025-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_remove_salaryrule_fixed_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryruleproduct',
            name='fixed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
