# Generated by Django 5.2.5 on 2025-08-25 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата смены')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('status', models.CharField(choices=[('OPEN', 'Открыта'), ('CLOSED', 'Закрыта')], default='OPEN', max_length=10, verbose_name='Статус смены')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_created', to=settings.AUTH_USER_MODEL, verbose_name='Создана менеджером')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Роль в смене (официант, повар, бармен, кальянный мастер, менеджер, санитарный инженер)')),
                ('check_in_time', models.DateTimeField(verbose_name='Время начала работы')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания работы')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift', verbose_name='Смена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Участие в смене',
                'verbose_name_plural': 'Участия в сменах',
                'unique_together': {('shift', 'user')},
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='participants',
            field=models.ManyToManyField(related_name='shifts_worked', through='shift.ShiftParticipation', to=settings.AUTH_USER_MODEL, verbose_name='Участники смены'),
        ),
        migrations.CreateModel(
            name='PlannedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('planned_start_time', models.TimeField(verbose_name='Плановое время начала')),
                ('planned_end_time', models.TimeField(verbose_name='Плановое время окончания')),
                ('role', models.CharField(max_length=50, verbose_name='Роль в смене (официант, повар и т.д.)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL, verbose_name='Внесено менеджером')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Запланированный сотрудник')),
            ],
            options={
                'verbose_name': 'Запланированная смена',
                'verbose_name_plural': 'Запланированные смены',
                'ordering': ['date', 'planned_start_time'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
