# Generated by Django 5.2.5 on 2025-10-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField(default='2025-10-01')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='employees',
            field=models.ManyToManyField(related_name='shifts', through='shift.ShiftEmployee', to='users.employee'),
        ),
    ]
