# Generated by Django 5.2.5 on 2025-10-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-date'], 'verbose_name': 'Work Shift', 'verbose_name_plural': 'Work Shifts'},
        ),
        migrations.AlterModelOptions(
            name='shiftemployee',
            options={'verbose_name': 'Shift-Employee Assignment', 'verbose_name_plural': 'Shift-Employee Assignments'},
        ),
        migrations.AlterUniqueTogether(
            name='shiftemployee',
            unique_together={('shift', 'employee', 'role')},
        ),
    ]
