# Generated by Django 5.2.5 on 2025-10-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poster_api', '0001_initial'),
        ('shift', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_api.cashshiftreport'),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
        migrations.AddField(
            model_name='shiftemployee',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='employees',
            field=models.ManyToManyField(related_name='shifts', through='shift.ShiftEmployee', to='users.employee'),
        ),
    ]
