# Generated by Django 5.2.5 on 2025-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_alter_shift_options_alter_shiftemployee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
