# Generated by Django 5.2.5 on 2025-09-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_api', '0006_workshop_delete_department_category_profit_and_more'),
        ('salary', '0002_alter_salaryrecord_unique_together_and_more'),
        ('shift', '0002_shift_revenue'),
        ('users', '0004_role_alter_user_role_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='shiftparticipation',
            name='shift',
        ),
        migrations.AlterUniqueTogether(
            name='shiftparticipation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shiftparticipation',
            name='user',
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_api.cashshiftreport')),
            ],
        ),
        migrations.DeleteModel(
            name='PlannedShift',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='ShiftParticipation',
        ),
    ]
