# Generated by Django 5.2.5 on 2025-08-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('manager', 'Менеджер'), ('employee', 'Сотрудник')], default='manager', max_length=10),
        ),
    ]
