# Generated by Django 5.2.5 on 2025-10-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа расчета ЗП',
                'verbose_name_plural': 'Группы расчета ЗП',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AddField(
            model_name='role',
            name='pay_group',
            field=models.ForeignKey(blank=True, help_text='Если указано, все сотрудники с ролями из этой группы будут делить ЗП между собой.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='users.paygroup', verbose_name='Группа расчета ЗП'),
        ),
    ]
