# Generated by Django 5.2.5 on 2025-10-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_paygroup_alter_role_options_role_pay_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='pay_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='users.paygroup', verbose_name='Группа расчета ЗП'),
        ),
    ]
