# Generated by Django 5.2.5 on 2025-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fullname_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Управляющий'), ('manager', 'Менеджер'), ('employee', 'Сотрудник'), ('waiter', 'Официант'), ('bartender', 'Бармен'), ('cook', 'Повар'), ('hookah', 'Кальянщик'), ('cleaner', 'Уборщик'), ('trainee', 'Стажер')], default='trainee', max_length=10),
        ),
    ]
